---
deployment:
  tasks:
    - export DEPLOYPATH=/home/myexpresscom/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/uploads/faturalar
    - /bin/mkdir -p $DEPLOYPATH/uploads/kurye-kanitlari
    - /bin/cp uploads/faturalar/.htaccess $DEPLOYPATH/uploads/faturalar/.htaccess
    - /bin/cp uploads/kurye-kanitlari/.htaccess $DEPLOYPATH/uploads/kurye-kanitlari/.htaccess
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R api $DEPLOYPATH
    - /bin/cp -R hesabim $DEPLOYPATH
    - /bin/cp -R hizmetler $DEPLOYPATH
    - /bin/cp -R migrations $DEPLOYPATH
    - /bin/cp -R panel $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp cozumler.html $DEPLOYPATH
    - /bin/cp cerez-politikasi.html $DEPLOYPATH
    - /bin/cp gizlilik-politikasi.html $DEPLOYPATH
    - /bin/cp hizmetler.html $DEPLOYPATH
    - /bin/cp iletisim.html $DEPLOYPATH
    - /bin/cp kurye-hizmet-sozlesmesi.html $DEPLOYPATH
    - /bin/cp kurye-gorev.php $DEPLOYPATH
    - /bin/cp kurye-kanit.php $DEPLOYPATH
    - /bin/cp kvkk-politikasi.html $DEPLOYPATH
    - /bin/cp nasil-calisir.html $DEPLOYPATH
    - /bin/cp sss.html $DEPLOYPATH
    - /bin/cp talep.html $DEPLOYPATH
    - /bin/cp talep-basarili.html $DEPLOYPATH
    - /bin/cp takip.html $DEPLOYPATH
    - /bin/cp teslimat-sartlari.html $DEPLOYPATH
    - /bin/cp ticari-elektronik-ileti-onayi.html $DEPLOYPATH
    - /bin/cp uyelik-sozlesmesi.html $DEPLOYPATH
    - /bin/cp yasakli-gonderiler.html $DEPLOYPATH
    - /bin/cp robots.txt $DEPLOYPATH
    - /bin/cp sitemap.xml $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp script.js $DEPLOYPATH
    - /bin/cp styles.css $DEPLOYPATH
